// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL0EVnBGJlc_56AODM2f_QHA7veBp4gL4',
    appId: '1:822443636636:web:2a3bd852eb184a0fab3a59',
    messagingSenderId: '822443636636',
    projectId: 'calendar-note-app-960be',
    authDomain: 'calendar-note-app-960be.firebaseapp.com',
    storageBucket: 'calendar-note-app-960be.firebasestorage.app',
    measurementId: 'G-EVCG279JJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL0EVnBGJlc_56AODM2f_QHA7veBp4gL4',
    appId: '1:822443636636:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '822443636636',
    projectId: 'calendar-note-app-960be',
    storageBucket: 'calendar-note-app-960be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL0EVnBGJlc_56AODM2f_QHA7veBp4gL4',
    appId: '1:822443636636:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '822443636636',
    projectId: 'calendar-note-app-960be',
    storageBucket: 'calendar-note-app-960be.firebasestorage.app',
    iosBundleId: 'com.example.calendarNoteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL0EVnBGJlc_56AODM2f_QHA7veBp4gL4',
    appId: '1:822443636636:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '822443636636',
    projectId: 'calendar-note-app-960be',
    storageBucket: 'calendar-note-app-960be.firebasestorage.app',
    iosBundleId: 'com.example.calendarNoteApp',
  );
}
